# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd63ee53513413c88f76f6e525ea43acfdcefe849d067d084b9b92eb309bfdd6d9e3e4181aa556e1969829150b1ba9dd3ac6aaeaa60306335cd60f61978e0bf8

test:
  secret_key_base: 6c95c5b1aac5e0720a485b48101220fd126f92354d2b51abe2ab6ad1d8a3c9cd191e82eda802d1dcb6b4bc7218f0bcd1c1a6ed634a2cc173a9b1bddc3aa7193d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
